export const SITE = {
  name: "ZihoTech",
  legalName: "Ziho Technologies",
  tagline: "AI-first software engineering for ambitious businesses.",
  email: "info.zihotech@gmail.com",
  phone: "+92 324 4793027",
  phoneRaw: "+923244793027",
  url: "https://zihotech.com",
  logo: "/logo.png",
  /**
   * Primary keyword set used across SEO meta tags and JSON-LD.
   * Covers brand variations (Ziho, Ziho Tech, Ziho Technologies, ZihoTech)
   * plus the core service taxonomy (AI dev, AIOps, RAG, custom software, etc).
   */
  keywords: [
    "Ziho",
    "Ziho Tech",
    "ZihoTech",
    "Ziho Technologies",
    "ZihoTech AI",
    "ZihoTech software",
    "AI engineering company",
    "AI development agency",
    "AIOps",
    "MLOps",
    "LLM engineering",
    "RAG pipelines",
    "AI consulting",
    "enterprise AI",
    "AI automation",
    "AI integration",
    "OpenAI integration",
    "LangChain development",
    "vector database",
    "AI agents",
    "generative AI",
    "machine learning consulting",
    "custom software development",
    "web application development",
    "mobile app development",
    "React development",
    "Next.js development",
    "Python AI development",
    "FastAPI",
    "Node.js development",
    "SaaS development",
    "MVP development",
    "enterprise software",
    "B2B SaaS",
    "fractional engineering",
    "software consulting US",
    "software consulting EU",
    "software consulting UK",
  ],
  social: {
    linkedin: "https://www.linkedin.com/company/zihotech",
    github: "https://github.com/zihotech",
    twitter: "https://x.com/zihotech",
    whatsapp: "https://wa.me/10000000000",
    calendly: "https://calendly.com/zihotech/discovery",
  },
};
